export {LoginPage} from "./Login/LoginPage"
export {NotesPage} from "./Notes/NotesPage"
export {HomePage} from "./Home/HomePage"
export {SignupPage} from "./Signup/SignupPage"
export {ArchivesPage} from "./Archive/ArchivesPage"